model_name: "facebook/sam-vit-base"

seed: 42
val_ratio: 0.2

patch_size: 256
step: 256
batch_size: 1 #20
num_workers: 2
positive_only: true
min_mask_sum: 20

epochs: 50
learning_rate: 0.01

checkpoint_dir: "./checkpoints"

loss_names: ["dice_ce", "dice_focal", "tversky"]
fine_tune_methods: ["lora", "mask_decoder"]
data_dir: "./data/trainValidation_set"

test_dir: "./data/test_set"
threshold: 0.5
test_results_csv: "test_results.csv"


visualization_slice_idx: null
auto_select_slice: true

visualization_dir: "prediction_visualizations"

models_to_visualize:
  - ["lora", "dice_focal"]